on:
  push:
    branches:
      - main

jobs:
  build-package-deploy:
    runs-on: self-hosted
    steps:
      - name: Restart bot service
        run: sudo systemctl restart what-to-play-bot.service
